### ISSUE TITLE
Unauthenticated access

### ISSUE THREAD

**Issue by jganovsky** [gizur/odataserver#1]
Is it possible to setup unauthenticated, non-https access to odataserver?

**Comment by colmsjo** [comment]
https can be turned on and off in the configuration file. You can try to create an anonymous user without password in mysql and then grant access to this user for the tables that should be public.

**Comment by jganovsky** [comment]
I was able to create an anonymous user and successfully logged into the MySQL db from another host as that user.  However when I attempt to access via odataserver I still get the following response:

{"d":{"error":"Invalid credentials, user or password missing. URL: /, headers: {\"host\":\"54.152.190.191\",\"connection\":\"keep-alive\",\"cache-control\":\"max-age=0\",\"accept\":\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\",\"user-agent\":\"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36\",\"accept-encoding\":\"gzip, deflate, sdch\",\"accept-language\":\"en-US,en;q=0.8\"} TYPE:service_def. See /help for help."}}

**Comment by colmsjo** [comment]
I have pushed a update that does not require username and password. See the README for how to work with anonymous users.
