### ISSUE TITLE
Request to provide better instructions for accessing a remote MySQL server

### ISSUE THREAD

**Issue by sezoko** [gizur/odataserver#2]
Hi, would it be possible to provide better instructions for setting up a remote MySQL server? And could you also confirm that the port of MySQL can be something else than 3306?

For example, I set the parameters of my remote MySQL server in the config.js file:

  c.RDBMS = {
    // DB admin/root username
    ADMIN_USER: process.env.ADMIN_USER,
    // MySQL admin/root password
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
    // DB host
    DB_HOST: '<somehost>',
    // MySQL port
    DB_PORT: '<someport>',
    // schema/database
    DATABASE: '<somedb>',
    // used by mssql only - options for mssql module
}

However, I am getting the following errors when trying to execute any curl command against my oData server:

{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","fatal":true}

Thanks much!

**Comment by colmsjo** [comment]
DB_HOST and DB_PORT are both empty in the config you've included. Enter IP-address and port.

**Comment by sezoko** [comment]
Sorry, I edited the values in my original message. Here is a closer example of what I have:
Do you think this config should work? 
  c.RDBMS = {
    // DB admin/root username
    ADMIN_USER: process.env.ADMIN_USER,
    // MySQL admin/root password
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
    // DB host
    DB_HOST: 'xyz.12345.xyz.rds.amazonaws.com',
    // MySQL port
    DB_PORT: '3306',
    // schema/database
    DATABASE: 'xswdb',
    // used by mssql only - options for mssql module
    OPTIONS: {
      encrypt: false // Use this if you're on Windows Azure
    }

I saw a reference in ADVANCED.md about this topic. Which 'supervisord.conf' is the blurb referring to? I am running on the Bitnami Node.js AMI in AWS, and my MySQL host is a managed service in RDS.

External MySQL
--------------

The included MySQL can be replaced with an external MySQL server. Disable the
internal MySQl server by commenting out the `[program:mysql]` parts with `#` in
`supervisord.conf`.

**Comment by colmsjo** [comment]
Are you using docker?



// mvh / best regards

Jonas Colmsjö | jonas@gizur.com | +46-707-924402 | @colmsjo | www.gizur.com

**Comment by sezoko** [comment]
No. Should I?

After installing oDataServer via "npm install odataserver" I am just launching it via "npm start"

Btw, I installed a mysql client on my Node.js app server and tested connectivity to my remote MySQL server via command line. It worked.

**Comment by colmsjo** [comment]
Did you set the environment variables with db username and password.

If you did, could you try to put this test.js and do node test.js?

```
var mysql      = require('mysql');
var connection = mysql.createConnection({
  host     : 'HOSTNAME',
  user     : 'USERNAME',
  password : 'PASSWORD'
});
 
connection.connect();
 
connection.query('SELECT 1 + 1 AS solution', function(err, rows, fields) {
  if (err) throw err;
 
  console.log('The solution is: ', rows[0].solution);
});
 
connection.end();
```

I see that I need to update the README.

**Comment by sezoko** [comment]
Will do. Can I also use a non-3306 port? How would I change this to include a custom port?

var connection = mysql.createConnection({
  host     : 'HOSTNAME',
  user     : 'USERNAME',
  password : 'PASSWORD'
});

**Comment by colmsjo** [comment]
This sections means that username and password is supplied via environment variables

```
ADMIN_USER: process.env.ADMIN_USER,
ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
```

You can replace it it with username and password in the file if you want. You can update DB_PORT to whatever port that you're using in Amazon RDS (but I think 3306 is the port they also are using if you haven't changed this).

**Comment by sezoko** [comment]
Just wanted to let you know that the test script worked. I was able to connect to my RDS database by executing node test.js. The result was "2" , as expected.

I wonder why I am getting errors when launching odataserver via
npm start &

I do have the user /password in "setenv"

export ADMIN_USER=[edited]
export ADMIN_PASSWORD=[edited]
export MAIL_USER=[edited]
export MAIL_PASSWORD=[edited]
NODE_DEBUG=debugtest,debugmysql,debugleveldb,debugodata,debugmain

and I already sent over the config.js with host/port info.

**Comment by swedenultimate** [comment]
Do 'echo $ADMIN_USER' and post the result.
