### ISSUE TITLE
http/1.1 406 not acceptable

### ISSUE THREAD

**Issue by lokesh1233** [gizur/odataserver#4]
Hi,

 http/1.1 406 not acceptable what is this EROOR,
while running in windows,

F:\git repository\gizur odataserver\gizur\odataserver>curl -v -u root:lokesh -XPOST -H -d '{"email":"yell.nagalokesh@gmail.com"}' http://localhost:9000/create_account;

[1/2]: 'email:yell.nagalokesh@gmail.come' --> <stdout>
--_curl_--'email:yell.nagalokesh@gmail.come'
* Rebuilt URL to: 'email:yell.nagalokesh@gmail.come'/
* Adding handle: conn: 0xa540d0
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0xa540d0) send_pipe: 1, recv_pipe: 0
* Could not resolve host: gmail.come'
* Closing connection 0
curl: (6) Could not resolve host: gmail.come'
* Adding handle: conn: 0xa540d0
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 1 (0xa540d0) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 9000 (#1)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9000 (#1)
* Server auth using Basic with user 'root'
> POST /create_account; HTTP/1.1
> Authorization: Basic cm9vdDpsb2tlc2g=
> User-Agent: curl/7.33.0
> Host: localhost:9000
> Accept: */*
>
< HTTP/1.1 406 Not Acceptable
< Content-Type: application/json
< Date: Mon, 29 Feb 2016 15:46:26 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
<
{"d":{"error":{},"message":"See /help for help."}}* Connection #1 to host localhost left intact

please help me..

Thanks for advance.

**Comment by colmsjo** [comment]
Have a look at https://github.com/gizur/odataserver2. I'm not maintaining this version anymore
