### ISSUE TITLE
./bin/run_tests.sh     '.' is not recognized as an internal or external command, in windows

### ISSUE THREAD

**Issue by lokesh1233** [gizur/odataserver#5]
HI,

F:\git repository\gizur\odataserver>npm test

> odataserver@0.2.6 test F:\git repository\gizur\odataserver
> ./bin/run_tests.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.

kindly help me.

**Comment by colmsjo** [comment]
It seams as though you are using windows. The scripts only works on osx/linux.

Also, please check out the new version of odataserver: https://github.com/gizur/odataserver2
